name: Docker Build & Publish

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Registry 🔑
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
          registry: gitea.andrejbarna.com

      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_DRUPAL_API_URL=${{ secrets.NEXT_PUBLIC_DRUPAL_API_URL }}
            NEXT_PUBLIC_CLIENT_ID=${{ secrets.NEXT_PUBLIC_CLIENT_ID }}
            NEXT_PUBLIC_CLIENT_SECRET=${{ secrets.NEXT_PUBLIC_CLIENT_SECRET }}
            NEXT_PUBLIC_GRANT_TYPE=${{ secrets.NEXT_PUBLIC_GRANT_TYPE }}
            NEXT_PUBLIC_REFRESH_GRANT_TYPE=${{ secrets.NEXT_PUBLIC_REFRESH_GRANT_TYPE }}
          tags: |
            gitea.andrejbarna.com/an-bar-dev/whereiskevin-react-frontend:${{ github.sha }}
            gitea.andrejbarna.com/an-bar-dev/whereiskevin-react-frontend:latest
